### ISSUE TITLE
does this repo need remote themes?

### ISSUE THREAD

**Issue by ErinBecker** [carpentries-incubator/jupyter-notebooks-intro#1]
@fmichonneau - This repo is in very early stages of development, and doesn't yet include any content. Do we need to enable remote themes here (as explained in [this Issue](https://github.com/carpentries-incubator/gap-lesson/issues/29))? Or does this repo already have it enabled?

**Comment by fmichonneau** [comment]
yes, it does. The current template doesn't have it implemented and therefore it needs to be enabled even if there is no content yet.
